### ISSUE TITLE
On reproducing results

### ISSUE THREAD

**Issue by 22209050** [SimonThomine/RememberingNormality#1]
Hello, firstly thank you very much for your work. But after I tried it, I found that the detection result is not very good, it is worse than the result in the paper, may I ask how is your actual detection result? Thank you for your reply.

**Comment by SimonThomine** [comment]
Hello,
Yes, I noticed that the results were not as good as the paper results. I may have some leads on why and I will try to improve the implementation. If you notice anything weird in the code or any missing part, please let me know.
