### ISSUE TITLE
change resnet 18 to  wide_resnet50_2

### ISSUE THREAD

**Issue by wjx213** [SimonThomine/RememberingNormality#4]
Hello,Thank you very much for your work. However, when I change 'resnet18' to 'wide_resnet50_2' in the 'config.yaml' file and run 'trainRM_RD.py', I encounter an error. May I ask how I can adjust other parameters if I want to change the backbone to 'wide_resnet50_2' so that the model can run? Thank you very much for your response.

**Comment by SimonThomine** [comment]
Hello, you're right, I forgot to adapt the memory modules for the wide resnet architecture (bottleneck instead of basicblock). The problem is now fixed. Please let me know if you encounter any other problem.

**Comment by wjx213** [comment]
thank you for your reply, the problem has been fixed，but the results differ slightly from the paper, but I'm still very grateful for your work!

**Comment by SimonThomine** [comment]
No problem :) Let me know if you find any problem in the code that could explain the slight difference in results.
