### ISSUE TITLE
I found some discrepancies in your code and the official paper

### ISSUE THREAD

**Issue by USTCXSC** [SimonThomine/RememberingNormality#5]
Firstly, you have done a fantastic job and thank you so much for your contribution!But I noticed a discrepancy between your code and the official paper.
<img width="283" alt="1715512299594" src="https://github.com/SimonThomine/RememberingNormality/assets/101544690/94a26fbc-4d6c-41ea-bf9d-12c1bfd23c69">
<img width="536" alt="1715512343086" src="https://github.com/SimonThomine/RememberingNormality/assets/101544690/760216b4-9dfb-4595-b665-1bf1c9fb4756">
I think we need to add "normality= True" here. I don't know if this is correct, I look forward to your answer!
<img width="590" alt="1715512465286" src="https://github.com/SimonThomine/RememberingNormality/assets/101544690/a4916458-01f8-4437-8413-0904725746c5">

**Comment by USTCXSC** [comment]
As described in the official paper, it really should have been added. But this would result in lower metrics on my personal dataset.

**Comment by SimonThomine** [comment]
You are right, thanks for the correction ! I update the code right now.

**Comment by SimonThomine** [comment]
[commit](https://github.com/SimonThomine/RememberingNormality/commit/b851e06d4e78fd71c91e677954de7765d2515fec)
